"""Render a project's Build Order: tracks of stages, one clickable page.

Canonical copy: ~/.claude/skills/build-order/render_build_order.py (vendor it
into each project's tools/ with render_build_order.css; do not fork the logic).

Sources (edit these, never the generated files): each track's
<folder>/stages.json, listed in the project's build-order.json.

Outputs:
  <track folder>/README.md and <track folder>/NN-<slug>.md   (one page per stage)
  the configured output HTML                                  (published as an artifact)

    python3 tools/render_build_order.py --config build-order.json
"""
import html
import json
import re
import string
from pathlib import Path

import argparse

# Project settings live in a small JSON file (default: build-order.json in the
# current directory), so this script is the same in every project:
#   {"title": "Build Order", "eyebrow": "...", "headline": "...", "standfirst": "...",
#    "output": "docs/product/build-order.html",
#    "artifact_url": "https://claude.ai/artifact/...",
#    "tracks": [{"key": "law", "name": "Law assistant", "folder": "docs/product/law-assistant"}]}
CONFIG = {}
STATUS = {"done": "Done", "now": "Building now", "next": "Next", "wait": "Waiting"}
MARK = {"y": "✓", "n": "·", "hold": "~"}


def sub_id(stage, index):
    return f"{stage['id']}{string.ascii_lowercase[index]}"


def stage_file(stage, position):
    return f"{position:02d}-{stage['slug']}.md"


def inline(text):
    return re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", html.escape(text))


def link_md(label, target):
    return f"[{label}]({target})" if target.startswith("http") else f"{label}: `{target}`"


def link_html(label, target):
    if target.startswith("http"):
        return f'<a href="{html.escape(target)}" target="_blank" rel="noopener">{html.escape(label)}</a>'
    return f"{html.escape(label)}: <code>{html.escape(target)}</code>"


def stage_md(stage, data):
    lines = [f"# {stage['id']} — {stage['name']}", "",
             f"**Status:** {STATUS[stage['status']]} · **Size:** {stage['size']} · [Back](README.md)", "",
             "## What it does", "", stage["does"], "", "## What you see", "", stage["see"], "",
             "## How we know it works", "", stage["proof"], "", "## Needs", ""]
    lines += [f"- {'✓' if n['met'] else '·'} {n['label']}" for n in stage["needs"]]
    lines += ["", "## Substages", ""]
    for i, item in enumerate(stage["items"]):
        detail = f" — {item['d']}" if item.get("d") else ""
        lines.append(f"- {MARK[item['s']]} **{sub_id(stage, i)}** {item['t']}{detail}")
    for key, heading in (("declaration", "Declared before code"), ("result", "Result")):
        if stage.get(key):
            lines += ["", f"## {heading}", "", stage[key]]
    if stage.get("links"):
        lines += ["", "## Related", ""] + [f"- {link_md(l, t)}" for l, t in stage["links"]]
    if stage.get("docs"):
        lines += ["", "## Records", ""] + [f"- `{d}`" for d in stage["docs"]]
    lines += ["", f"_Generated by `tools/render_build_order.py` from `stages.json`; edit the JSON. Updated {data['updated']}._", ""]
    return "\n".join(lines)


def readme_md(name, data):
    done = sum(1 for s in data["stages"] if s["status"] == "done")
    lines = [f"# {name} — Build Order", "", data["rule"], "",
             f"**{done} of {len(data['stages'])} stages done.** The clickable page covering every "
             f"track is `{CONFIG.get('output', 'build-order.html')}`"
             + (f" ({CONFIG['artifact_url']})" if CONFIG.get("artifact_url") else "") + ".", "",
             "| Stage | What | Status | Substages | Size |", "|---|---|---|---|---|"]
    for pos, s in enumerate(data["stages"]):
        subs_done = sum(1 for i in s["items"] if i["s"] == "y")
        lines.append(f"| {s['id']} | [{s['name']}]({stage_file(s, pos)}) | {STATUS[s['status']]} | "
                     f"{subs_done}/{len(s['items'])} | {s['size']} |")
    if data.get("alongside"):
        lines += ["", "## Alongside", ""] + [f"- {a}" for a in data["alongside"]]
    lines += ["", "_Generated by `tools/render_build_order.py`; edit `stages.json`._", ""]
    return "\n".join(lines)


def card_html(stage):
    status = stage["status"]
    needs = "".join(f'<span class="dep{" met" if n["met"] else ""}">{html.escape(n["label"])}</span>'
                    for n in stage["needs"])
    subs = "".join(
        f'<li class="{i["s"]}"><span class="sid">{sub_id(stage, k)}</span>'
        f'<span>{inline(i["t"])}{(" <em>" + inline(i["d"]) + "</em>") if i.get("d") else ""}</span></li>'
        for k, i in enumerate(stage["items"]))
    done = sum(1 for i in stage["items"] if i["s"] == "y")
    extra = ""
    for key, heading in (("declaration", "Declared before code"), ("result", "Result")):
        if stage.get(key):
            extra += f'<div class="block"><h4>{heading}</h4><p>{inline(stage[key])}</p></div>'
    if stage.get("links"):
        extra += '<div class="block"><h4>Related</h4><p>' + "<br>".join(
            link_html(l, t) for l, t in stage["links"]) + "</p></div>"
    if stage.get("docs"):
        extra += '<div class="block"><h4>Records</h4><p>' + "<br>".join(
            f"<code>{html.escape(d)}</code>" for d in stage["docs"]) + "</p></div>"
    opened = " open" if status in ("now", "next") else ""
    return f"""
<details class="stage {status}" id="stage-{html.escape(stage['id'])}"{opened}>
  <summary>
    <span class="letter">{html.escape(stage['id'])}</span>
    <span class="head">
      <span class="shead"><span class="sname">{html.escape(stage['name'])}</span>
        <span class="pill {status}">{STATUS[status]}</span>
        <span class="count">{done} / {len(stage['items'])} substages · {html.escape(stage['size'])}</span></span>
      <span class="needs"><span class="needs-label">Needs</span>{needs}</span>
    </span>
    <span class="chev" aria-hidden="true"></span>
  </summary>
  <div class="body">
    <div class="block"><h4>What it does</h4><p>{inline(stage['does'])}</p></div>
    <div class="grid2">
      <div class="block"><h4>What you see</h4><p>{inline(stage['see'])}</p></div>
      <div class="block"><h4>How we know it works</h4><p>{inline(stage['proof'])}</p></div>
    </div>
    <div class="block"><h4>Substages</h4><ul class="subs">{subs}</ul></div>
    {extra}
  </div>
</details>"""


CSS = Path(__file__).with_name("render_build_order.css").read_text(encoding="utf-8")


def page_html(tracks):
    tabs, panels = [], []
    total_done = total = 0
    for i, (key, name, data) in enumerate(tracks):
        done = sum(1 for s in data["stages"] if s["status"] == "done")
        now = sum(1 for s in data["stages"] if s["status"] == "now")
        n = len(data["stages"])
        total_done += done
        total += n
        selected = "true" if i == 0 else "false"
        tabs.append(f'<button type="button" role="tab" id="tab-{key}" aria-controls="panel-{key}" '
                    f'aria-selected="{selected}" data-track="{key}">{html.escape(name)}'
                    f'<span class="tabcount">{done}/{n}</span></button>')
        cards = "".join(card_html(s) for s in data["stages"])
        along = "".join(f"<li>{inline(a)}</li>" for a in data.get("alongside", []))
        along_html = f'<h3>Alongside</h3><ul class="along">{along}</ul>' if along else ""
        panels.append(f"""
<section role="tabpanel" id="panel-{key}" aria-labelledby="tab-{key}"{'' if i == 0 else ' hidden'}>
  <p class="rule">{inline(data['rule'])}</p>
  <div class="overall"><div class="obar"><span class="oseg d" style="width:{done / n * 100:.0f}%"></span><span class="oseg n" style="width:{now / n * 100:.0f}%"></span></div>
    <div class="okey"><span><b>{done}</b> of {n} done</span><span><b>{now}</b> building now</span></div></div>
  <div class="tools"><button type="button" class="open-all">Open all</button><button type="button" class="close-all">Close all</button></div>
  <div class="stages">{cards}</div>
  {along_html}
</section>""")
    updated = max(data["updated"] for _, _, data in tracks)
    return f"""<title>{html.escape(CONFIG.get('title', 'Build Order'))}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,600;1,6..72,400&family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Sans+Arabic:wght@400;600&display=swap">
<style>{CSS}</style>
<div class="wrap">
<header>
  <p class="eyebrow">{html.escape(CONFIG.get('eyebrow', ''))} · {html.escape(updated)}</p>
  <h1>{CONFIG.get('headline', "What's built, and <em>what's next</em>")}</h1>
  <p class="standfirst">{inline(CONFIG.get('standfirst', 'Pick a track, then click any stage for what it does, what you will see, how we will know it works, what it waits on, and its substages.'))} <b>{total_done} of {total}</b> stages done overall.</p>
  <div class="tabs" role="tablist" aria-label="Tracks">{''.join(tabs)}</div>
</header>
{''.join(panels)}
<footer>Generated by <code>tools/render_build_order.py</code> from each track's <code>stages.json</code>. Every stage also has its own page in its track's folder: {', '.join('<code>' + html.escape(t['folder']) + '/</code>' for t in CONFIG.get('tracks', []))}.</footer>
</div>
<script>
const tabs=[...document.querySelectorAll('[role=tab]')];
function show(key,push){{tabs.forEach(t=>{{const on=t.dataset.track===key;t.setAttribute('aria-selected',on);document.getElementById('panel-'+t.dataset.track).hidden=!on;}});
  if(push){{try{{history.replaceState(null,'','#'+key)}}catch(e){{}}}}}}
tabs.forEach(t=>t.addEventListener('click',()=>show(t.dataset.track,true)));
tabs.forEach((t,i)=>t.addEventListener('keydown',e=>{{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){{const n=tabs[(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];n.focus();show(n.dataset.track,true);}}}}));
document.querySelectorAll('.open-all').forEach(b=>b.addEventListener('click',()=>b.closest('section').querySelectorAll('details').forEach(d=>d.open=true)));
document.querySelectorAll('.close-all').forEach(b=>b.addEventListener('click',()=>b.closest('section').querySelectorAll('details').forEach(d=>d.open=false)));
const h=location.hash.slice(1);
if(tabs.some(t=>t.dataset.track===h))show(h,false);
else if(h){{const d=document.getElementById(h);if(d){{show(d.closest('section').id.replace('panel-',''),false);d.open=true;d.scrollIntoView();}}}}
</script>
"""


def main():
    parser = argparse.ArgumentParser(description="Render a project's Build Order.")
    parser.add_argument("--config", default="build-order.json")
    args = parser.parse_args()
    config_path = Path(args.config).resolve()
    CONFIG.update(json.loads(config_path.read_text(encoding="utf-8")))
    base = config_path.parent if CONFIG.get("relative_to") == "config" else Path.cwd()
    tracks = []
    for track in CONFIG["tracks"]:
        key, name, folder = track["key"], track["name"], base / track["folder"]
        data = json.loads((folder / "stages.json").read_text(encoding="utf-8"))
        (folder / "README.md").write_text(readme_md(name, data), encoding="utf-8")
        for pos, stage in enumerate(data["stages"]):
            (folder / stage_file(stage, pos)).write_text(stage_md(stage, data), encoding="utf-8")
        tracks.append((key, name, data))
    (base / CONFIG["output"]).write_text(page_html(tracks), encoding="utf-8")
    print("rendered", ", ".join(f"{n}: {len(d['stages'])} stages" for _, n, d in tracks))


if __name__ == "__main__":
    main()
